import type { Metadata } from "next";
import { Geist, Inter, Poppins, Source_Serif_4 } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/components/ConvexClientProvider";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { OnboardingGuard } from "@/components/guards/OnboardingGuard";
import NavBar from "@/components/landing-page/navigation/nav-bar";

const sourceSerif4 = Source_Serif_4({
  subsets: ["latin"],  
  weight: ["200", "300", "400", "700", "800", "900"],
   variable: "--font-serif",
});

const interFont = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "700"],
   variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Simple Invoice PH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en">
        <body
          className={`${sourceSerif4.variable} ${interFont.variable} antialiased`}
        >
          <ConvexClientProvider>
            <OnboardingGuard>
              <NavBar/>
              {children}</OnboardingGuard>
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
